---
- name: start service
  hosts: web
  remote_user: root
  tasks:
  - name: start httpd service
    service:
      name: httpd
      state: started
  - name: modify index.html
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify:
      - restart httpd
    when:
      ansible_facts['nodename'] == "web69-server.com"
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted