- name: shutdown service 
  hosts: web
  remote_user: root
  tasks:
  - name:  shutdown httpd service
    service:
      name: httpd
      state: stopped
    when: 
      #ansible_facts['all_ipv4_addresses'] == "192.168.218.69"
      ansible_facts['nodename'] == "bogon"



    